### ISSUE TITLE
"TypeError: A valid JSON object must be specified" error with arrays containing string values in redactyl.js after updating from version 1.4.3

### ISSUE THREAD

**Issue by FilipHavel** [rcjpisani/redactyl.js#19]
Hello,

I am experiencing an error after updating to higher versions from version 1.4.3 in `redactyl.js`. Specifically, I am getting a `TypeError: A valid JSON object must be specified` error when inserting an object into the `redact` function. The object looks like this:

```javascript
redactyl.redact({
    emails: ['patchtest@email.com']
})
```

This object worked perfectly fine in version 1.4.3, but after updating, the error started to occur. Interestingly, if I create a property in the object that looks like this: `emails: [{ email: 'patchtest@email.com' }]`, the error is not thrown. So, it seems that the problem is caused when the property is an array with string values.

Any help resolving this issue would be greatly appreciated.

Thank you.

**Comment by Diorbert** [comment]
Hi, @FilipHavel . Thank you for posting this issue. I'm facing the same issue under the same circumstances.

**Comment by Cal-Morris** [comment]
Looks to have been introduced through https://github.com/rcjpisani/redactyl.js/pull/14.

Happy to raise PR and get this sorted if needed!
